### Importing Libraries

In [1]:
import math
import numpy as np
import pandas as pd

### Importing Dataset

In [2]:
data = pd.read_csv('50_Startups.csv')

In [3]:
data.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

##### Distuguishing between Independent and Dependent Variables

In [4]:
x = data.iloc[:,:-1].values
y = data.iloc[:,4].values

###### Encoding categorical Data

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
le = LabelEncoder()

In [7]:
x[:,3] = le.fit_transform(x[:,3])

In [8]:
ohe = OneHotEncoder()

In [9]:
x = ohe.fit_transform(x).toarray()

In [10]:
x = x[:,1:]

In [11]:
x

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.]])

###### Splitting data in Training and Testing Set

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

##### Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)
x_test = sc_X.transform(x_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1,1))

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
regressor = LinearRegression()

In [17]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
y_pred = regressor.predict(x_test)

In [19]:
y_pred

array([[-0.03847627],
       [-0.16777101],
       [-0.03582068],
       [-0.03641594],
       [-0.03519527],
       [ 0.06536523],
       [ 0.06399281],
       [ 0.05580609],
       [-0.03133212],
       [-0.03519527]])

# Second Example for Multivariate Regression Analysis

In [20]:
data2 = pd.read_csv('Monroe_Township.csv')

In [21]:
data2

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

###### Handling null values

In [22]:
median_bedroom = math.floor(data2['bedrooms'].median())

In [23]:
median_bedroom

3

In [24]:
data2['bedrooms'] = data2['bedrooms'].fillna(median_bedroom)

In [25]:
data2

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

###### Differentiating in dependent and independent variables

In [26]:
X = data2.iloc[:,:-1].values
Y = data2.iloc[:,3].values

In [27]:
X

array([[2.6e+03, 3.0e+00, 2.0e+01],
       [3.0e+03, 4.0e+00, 1.5e+01],
       [3.2e+03, 3.0e+00, 1.8e+01],
       [3.6e+03, 3.0e+00, 3.0e+01],
       [4.0e+03, 5.0e+00, 8.0e+00]])

In [28]:
Y

array([550000, 565000, 610000, 595000, 760000], dtype=int64)

In [29]:
regressor.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
regressor.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [31]:
regressor.intercept_

383724.9999999998

In [32]:
regressor.predict([[2600,3,20]])

array([526000.])

In [33]:
regressor.predict([[3000,3,40]])

array([444400.])

##### Cross checking the values

In [34]:
(137.25*3000) + (-26025*3) + (-6825*40) + 383724.9999999998

444399.9999999998